# Generated by Django 2.1.8 on 2019-04-23 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extractor_app', '0002_auto_20190423_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquesession',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='uniquesession',
            unique_together={('user', 'sessionid', 'inputted_text', 'list_title', 'qa_list')},
        ),
    ]
