# Generated by Django 2.1.8 on 2019-04-25 16:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extractor_app', '0005_auto_20190424_1731'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together={('user', 'list_title', 'qa_list')},
        ),
        migrations.AlterUniqueTogether(
            name='uniquesession',
            unique_together={('user', 'sessionid')},
        ),
    ]
