# Generated by Django 2.1.8 on 2019-05-19 12:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extractor_app', '0006_auto_20190425_1726'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together={('user', 'list_title')},
        ),
    ]
