# Generated by Django 2.1.8 on 2019-04-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=256, null=True)),
                ('inputted_text', models.TextField(blank=True, null=True)),
                ('qalist', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sessionid', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('username', 'sessionid', 'inputted_text', 'qalist')},
        ),
    ]
