# Generated by Django 2.1.8 on 2019-04-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0002_useranswer_creationuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='creationuser',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
