# Generated by Django 2.1.8 on 2019-04-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0003_auto_20190424_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='username',
            new_name='usersname',
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('usersname', 'sessionid', 'inputted_text', 'qalist')},
        ),
    ]
