# Generated by Django 2.1.8 on 2019-04-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0004_auto_20190424_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='usersname',
            new_name='username',
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('username', 'sessionid', 'inputted_text', 'qalist')},
        ),
    ]
