# Generated by Django 2.1.8 on 2019-04-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0005_auto_20190424_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='averagegrade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
