# Generated by Django 2.1.8 on 2019-04-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_handler', '0006_useranswer_averagegrade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('username', 'sessionid', 'qalist')},
        ),
    ]
